### ISSUE TITLE
No module named 'utils.file_ops'

### ISSUE THREAD

**Issue by bemoregt** [zblasingame/ADD-GAN#1]
Hi, @zblasingame 

I met this error:

sgiO2:ADD-GAN sgi320$ python3 test_all.py 
Traceback (most recent call last):
  File "test_all.py", line 1, in <module>
    import utils.file_ops as fops
ModuleNotFoundError: No module named 'utils.file_ops'
sgiO2:ADD-GAN sgi320$ 

what's wrong wit me?

Thanks.

**Comment by zblasingame** [comment]
@bemoregt 

Sorry for the belated reply.
I forgot to  commit the `__init__.py` files that make python directories packages.

It should work now.

**Comment by bemoregt** [comment]
Hi, @zblasingame 

It's same error whith your new commited code.

Like this:

kraken:ADD-GAN dti$ python3 test_all.py 
Traceback (most recent call last):
  File "test_all.py", line 1, in <module>
    import utils.file_ops as fops
ModuleNotFoundError: No module named 'utils.file_ops'

**Comment by zblasingame** [comment]
@bemoregt,

It should be fixed now, there was a name change recently and I haven't used that test script in a while. Additionally, the datasets my lab uses aren't available to the public yet so the script won't work as it will search for non-existent datasets.
