### ISSUE TITLE
Is there a paper for ADD-GAN?

### ISSUE THREAD

**Issue by oyxhust** [zblasingame/ADD-GAN#2]
Is there a paper for ADD-GAN? Could you give me a arxiv link?

**Comment by zblasingame** [comment]
We are currently working on a paper on the ADD-GAN. Due to finals we haven't had time to put anything up on arxiv yet. We are hoping to by mid January at the latest.

**Comment by oyxhust** [comment]
Thanks a lot!  I am working on gan based anomaly detection, and hope to see your paper soon :). I think it will be an interesting paper.

**Comment by purpose-driven-engineer** [comment]
This is an amazing project. Really interesting.

**Comment by Santana18** [comment]
Did you put something on arxiv by now?

**Comment by zblasingame** [comment]
This work was absorbed into other work we did on anomaly detection: [https://camel.clarkson.edu/publications.html](https://camel.clarkson.edu/publications.html)
